apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: exceptions.spdx.softwarecomposition.kubescape.io
spec:
  group: spdx.softwarecomposition.kubescape.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            payload:
              x-kubernetes-preserve-unknown-fields: true
  scope: Cluster
  names:
    plural: exceptions
    singular: exception
    kind: Exception
    shortNames:
    - except