name: build
on:
  pull_request:
    types: [closed]
    branches: 
    - 'main'
    paths-ignore:
      - '**.md' ### Ignore running when README.MD changed.
      - '.github/workflows/*' ### Ignore running when files under path: .github/workflows/* changed.

  # push:
  #   tags:
  #     - 'v*'

jobs:
  pr-merged:
    if: ${{ github.event.pull_request.merged == true }} ## Skip if not merged to master
    uses: kubescape/workflows/.github/workflows/incluster-comp-pr-merged.yaml@main
    with:
      IMAGE_NAME: quay.io/${{ github.repository_owner }}/operator
      IMAGE_TAG: v0.1.${{ github.run_number }}
      COMPONENT_NAME: operator
      SYSTEM_TESTS_BRANCH: master
      CGO_ENABLED: 0
      GO111MODULE: ""
      BUILD_PLATFORM: linux/amd64,linux/arm64
      GO_VERSION: "1.20"
      REQUIRED_TESTS: '[
                        "vulnerability_scanning", 
                        "vulnerability_scanning_trigger_scan_on_new_image", 
                        "vulnerability_scanning_trigger_scan_public_registry", 
                        "vulnerability_scanning_trigger_scan_public_registry_excluded", 
                        "vulnerability_scanning_trigger_scan_private_quay_registry", 
                        "vulnerability_scanning_triggering_with_cron_job", 
                        "registry_scanning_triggering_with_cron_job", 
                        "ks_microservice_ns_creation",
                        "ks_microservice_on_demand", 
                        "ks_microservice_mitre_framework_on_demand", 
                        "ks_microservice_nsa_and_mitre_framework_demand", 
                        "ks_microservice_triggering_with_cron_job", 
                        "ks_microservice_update_cronjob_schedule", 
                        "ks_microservice_delete_cronjob", 
                        "ks_microservice_create_2_cronjob_mitre_and_nsa",
                        "vulnerability_scanning_test_public_registry_connectivity_by_backend",
                        "vulnerability_scanning_test_public_registry_connectivity_excluded_by_backend",
                        "relevantCVEs",
                        "relevancy_enabled_stop_sniffing",
                        "relevant_data_is_appended",
                        "relevancy_large_image",
                        "relevancy_extra_large_image",
                        "relevancy_fix_vuln",
                        "relevancy_python",
                        "relevancy_golang",
                        "relevancy_java",
                        "relevancy_java_and_python",
                        "relevancy_golang_dynamic"
                        ]'   
      HELM_E2E_TEST: true
      COSIGN: true   
    secrets: inherit
